epezent/implot

implot_demo.cpp

Add stdlib.h - fixes rand(), srand() and RAND_MAX on VC

---

implot.cpp
implot.h
implot_demo.cpp

Plot digital channels as float (only positive values)

PlotDigital multi level

---

implot.cpp

On my system this bumps FPS from 360 to 410 using stress test plots in demo function

call getter, transformer and cull test once per point instead of twice

---

implot.cpp

FitThisFrame in PlotDigital it' not necessary due to actual nature of digital plot.

PlotDigital vs FitThisFrame

---

implot.cpp
implot.h
implot_demo.cpp

removed conversions from float to double and back. removed static text buffers, use of secure sprintf functions under visual studio, float-to-int conversions (please check that)

warning fixes

---

implot.cpp

ImVec2() markers vector initialization

v0.3 C++11 extension warnings

---

implot.cpp
implot.h
implot_demo.cpp

Vertical and Horizontal error bars

---

implot.cpp

Fix circular buffer rollover (issue #60)

Fix circular buffer rollover (issue #60)

---

implot.cpp
implot.h
implot_demo.cpp

Returns true if plot item is highlight
PS: how to force "highlight"? Push or SetNext?

IsPlotItemHighlight, IsPlotXAxisHovered, IsPlotYAxisHovered

---

implot.cpp

PlotText color properties inherited from ImGuiCol_Text, so it can be customized by `ImGui::PushStyleColor(ImGuiCol_Text, <myColor>);`

PlotText color

---

implot.cpp
implot_internal.h

ImPlotTimeFmt_HrMinSMs,        // 7:21:29.428pm (19:21:29.428)

ImPlotTimeFmt_HrMinSMs time format

---

implot.cpp
implot.h

Done as mentioned in issue #126

Addition of va_list V versions of Annotate and AnnotateClamped

---

implot.cpp
implot.h
implot_demo.cpp
implot_internal.h
implot_items.cpp

Adds ability to set legend location and orientation. Can be any corner inside or outside of the plot, with items listed vertically or horizontally.

Configurable Legend Locations

---

implot.h
implot_demo.cpp
implot_items.cpp

Add Stairstep Plots

---

implot.cpp

Fixes #174
Hi Evan, here is a suggested fix. This will give more control over styling to the end user. We hit this while integrate some themes into [Dear PyGui](https://github.com/hoffstadt/DearPyGui). Let me know your thoughts on this, Thanks!

[#174] DatePicker disabled color

---

implot.cpp
implot.h
implot_demo.cpp
implot_internal.h

[WIP] This PR improves drag and drop support for ImPlot. I am aiming to make plots, axes, and legends both sources and targets. So far all targets are working. I still need to find a workaround for sources.

Improved Drag and Drop Support

---

backends/implot_backend.h
backends/implot_impl_opengl3.cpp
implot_items.cpp

I merged `SetHeatmapData()`, `RenderHeatmap()` and `SetAxisLog()` in a single function as requested. I also took this opportunity to do a bit of a cleanup and do some small optimizations which I think give something like a 1% improvement in FPS. I deviated a bit from the template proposed in [here](https://github.com/epezent/implot/discussions/261#discussioncomment-961244) in order to reduce the number of parameters where possible.

Backends: Implement heatmap rendering in a single function

---

implot_internal.h

hi, i needed this to do things like
thread_local ImPlotContext* ImPlotThreadLocalContext;
#define GImPlot ImPlotThreadLocalContext
i'm not sure if this is the best way to achieve it though.
cheers.

more flexible custom context management

---

implot.cpp
implot.h
implot_demo.cpp

Fix for commit https://github.com/ocornut/imgui/commit/2c03aac6d30720d8f717dcd9cbb8b9a6799396b8 on master

Fix for 1.88 WIP (18716) renaming ImGuiKeyModFlags to ImGuiModFlags

---

implot.cpp

This seems to be a typo when merging from https://github.com/epezent/implot/pull/365

fix merge typo in Locator_Time()

---

TODO.md
implot.h
implot_demo.cpp
implot_items.cpp

This PR add the `ImPlotPieChartFlags_Exploding` flag to the pie chart so that when you hover the legend, the corresponding item in the chart explodes

feat: add `ImPlotPieChartFlags_Exploding`

---

implot.h

#319 updated the lambda example but did not update the free function example creating a bit of confusion.

Fix MyDataGetter example after #319
