epezent/implot

implot.cpp

warning: left operand of comma operator has no effect [-Wunused-value]
`if (plot.Selecting && (plot.Flags, ImPlotFlags_Selection)) {`
`~~~~~~~~~~~~~~~~~~~~~~^~~~~`

BOX-SELECTION HasFlag() missing

---

implot.cpp

In C/C++ NAN == NAN is false, so isnan() must be used to identify NAN values.

Identify NANs with isnan()

---

implot.cpp
implot.h
implot_demo.cpp

This allows up to 3 Y axes to be used, one on the left side, and up to
2 on the right.  To use multiple axes, one of the `ImPlotFlags_Y2Axis`
or `ImPlotFlags_Y3Axis` must be passed to `BeginPlot`.  Then, before
each Plot call, SetPlotYAxis may be used to set that plot on an
alternate axis.
An extra line and ticks are rendered off to the right if all 3 axes
are configured (although those ticks are always only 5 long,
regardless of major status).  Each of the axes, when present, has a
(possibly invisible if ticks and labels are disabled) hit target that
can be used to scroll and scale that axis independently.
Some other changes were required to make this happen:
* Queries are now only in pixel coordinates
* ImPlotRange has been renamed to ImPlotBounds (and correspondingly
GetPlotRange is …

Support multiple Y axes simultaneously

---

implot.cpp
implot.h
implot_demo.cpp

This PR tidies up @jpieper's fine work for multiple y-axis support, among other small refinements. Compared to https://github.com/epezent/implot/pull/25, I made the following changes:
- I fixed the drag behavior so that only the axis clicked will ever be dragged
- There were some issues with the clip rects in `EndPlot`. Those have been fixed. 
- Box-selection for all y-axes was only based on the first y-axis. Each axis now has its range rescaled independently when box selection is confirmed.
- By setting `plot.Flags` each frame, and not inside of `if(just_created)`, it was not longer possible to toggle the legend and other settings from the context menu. My solution was to cache the previous frame's flags, and do a check to see if the user has programmatically changed their input flags. …

Integrate Multiple Y-Axis Support

---

implot.cpp

. Fix assert messages for "Needs to be called between BeginPlot() and EndPlot()"
. PlotDigital gap initialization
. PlotDigital data extents disabled (digital channels are "pixel based")

Assert messages, PlotDigital gap and data extents

---

implot.cpp

implot.cpp:3382:26: error: definition of variable with array type needs an explicit size or an initializer
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix

Fix compile under MacOs

---

implot.cpp
implot.h

Hello,
**First of**; great library. Thank you so much for writing it, and sharing it with the community. It's already incredibly useful for us.
**Second;** I don't expect this pull-request to be accepted in its current form. While my changes currently serve our needs, consider it a rough sketch at best. I hope it can start a discussion on whether ImPlot even needs support for input remapping, and if so, how to best do that.
**Some background**: we integrated ImPlot in an already complex application that has existing input-bindings for things like select, zoom, and pan. We use the same input patterns across a variety of different 2D and 3D panels, and our users have certain expectations as to what Left/Right/Middle mouse buttons do, as well as Ctrl/Alt/Shift modifier keys.
To be more …

Support for input remapping (mouse-buttons/modifiers-keys).

---

implot.cpp

Does this seem reasonable?  I wanted some plot items to have no legend, and just prefixing them with `##` otherwise leaves a blank colored line in the legend bar.

Only display non-empty legends

---

implot.cpp

The new values were being stored in PreviousFlags instead of Flags.
I don't understand the PreviousFlags logic in general, is the idea to have PreviousFlags be the flags before any double-right-click popup menu modifications?

Fix yaxis setting updates not working

---

implot.cpp

For backends that don't support `VtxOffset` (the imgui emscripten example) we are forced to use a 32bit index buffer instead. This patch fixes an issue from #41 where the calculation of the maximum index would overflow. The benchmark plot now renders correctly in the emscripten example when compiling with `-DImDrawIdx="unsigned int"`.

Fix overflow when using 32-bit ImDrawIdx

---

implot_demo.cpp

implot_demo.cpp:1012:69: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]

Fix compiler warning in implot_demo.cpp

---

implot.cpp

The query rectangle is drawn regardless of whether ImPlotFlags_Query is included within ImPlotFlags.
This is quite unintuitive when I do a query and later disable query mode. It would be cleaner if the query rectangle disappears altogether!

Draw query rect only when query enabled.

---

implot.cpp
implot.h
implot_demo.cpp

This uses pieces of the ImGui BeginDragDropSource implementation to
provide a method to drag from a legend entry.
EndDragDropSource is just a wrapper around ImGui::EndDragDropSource.

Add BeginLegendDragDropSource

---

implot.cpp
implot.h
implot_demo.cpp

EndPopup is just a wrapper around ImGui::EndPopup.
BeginPopupContextLegend provides easy-to-use context menus for legend
entries along the lines of ImGui::BeginPopupContextItem.

Add BeginPopupContextLegend and EndPopup

---

implot.cpp
implot.h
implot_demo.cpp

For my application I needed a horizontal reference line that could be adjusted by dragging it with the mouse. To do this I added an invisible button and detect when that button is being dragged. In order for this to work I needed to modify ImPlot to tell `ImGui::ItemAdd` what our ID is, and then check for if `HoveredIdPreviousFrame` matches our ID. If it does not match that indicates that the mouse is actually hovering a widget added on top of us. I'm not sure why `ImGui::ItemHoverable` does not check this by default?
I've included a demo of a horizontal line movable via click and drag.

Handle possibly overlapping widgets added via ImGui::SetItemAllowOverlap()

---

implot_items.cpp

I got annoyed at the warnings I got compiling with GCC 10.2.0. 
If there's a better way to solve this let me know, but I figured
this was the simplest and best way. :D

Don't redeclare IM_NORMALIZE2F_OVER_ZERO unnecessarily

---

implot.cpp
implot.h

Option for not rendering the title of the graph.
I needed a small form factor bar chart. Setting the flag results in:

Option for not rendering the title of the graph.

---

implot.cpp

My compiler (or the settings I use) throws some "if does not guard..." warnings here and insists on putting explicit {} blocks.
I like it better that way, too. :-)
Feel free to use or discard.

fix compiler warning re. 'if does not guard...'

---

implot.cpp

This is an extremely simple fix, I am open to changing it. The reason the current logic does not work is that if the `plot.XAxis.Range.Max` happens to be zero, nothing will happen. I reasoned that we don't really need to shift ranges by some percentage of the max value, we just center it.

Center constant data when fitting.

---

implot_demo.cpp

Several `CollapsingHeader()` use same label as `BeginPlot()`. This creates an ID collision, which confuses Dear ImGui testing engine. Added `##` in `CollapsingHeader()` label are included in ID calculation, but discarded when rendering. This gives affected `CollapsingHeader()` a different ID and solves ID collision.

Fix ID collisions in the demo

---

implot.cpp
implot.h
implot_demo.cpp

This is how the new demo looks like:

Allow second and third axes to have labels

---

README.md
implot.cpp
implot.h
implot_internal.h

This PR also removes `ImPlotInputMap` from the public API. It can still be found in `implot_internal.h`.

Make context menus open with single right-click instead of double right-click

---

implot.cpp

Similar to your Drag and Drop demo I have a drag and drop plot setup where the user can select from a number of variables to plot. I want them to be able to drop one variable on the x-axis (and use that as the x variable). For that I thought highlighting the x-axis like the y-axes would be good.
I'm not insisting on this pull request being merged. I can maintain that patch in my project, no problem. But I thought it could be useful thing to have.
I'm not sure how that fits your concept. Perhaps you'd prefer this to be an option (ImPlotFlags or ImPlotAxisFlags perhaps)?
Please advise.

render x-axis drag/drop hover

---

implot.cpp
implot_items.cpp

- Fix to support recently renamed flags ImDrawCornerFlags_All -> ImDrawFlags_RoundCornersAll.
In order to support codebases with IMGUI_DISABLE_OBSOLETE_FUNCTIONS we attempt to use the new symbol when available, else define new name to old name. Fix is not required is user doesn't set IMGUI_DISABLE_OBSOLETE_FUNCTIONS .
Note that for this specific change, code designed for 1.82+ (aka regular user code) can now use the default 0 to signify "all round corners". As I imagine implot wants to target older versions we keep the explicit flags.
- Fix one misuse of `ImGui::Value()` in Metrics (was calling the const char* + bool version erroneously, I guess leading to the `%s` bit being displayed to user.

Fix for draw corners renames in imgui master + fix misuse of ImGui::Value()

---

implot.cpp
implot.h
implot_demo.cpp
implot_internal.h

```cpp
// Set the format for numeric X axis labels (default="%g"). Formated values will be doubles (i.e. don't supply %d, %i, etc.). Not applicable if ImPlotAxisFlags_Time enabled.
void SetNextPlotFormatX(const char* fmt);
// Set the format for numeric Y axis labels (default="%g"). Formated values will be doubles (i.e. don't supply %d, %i, etc.).
void SetNextPlotFormatY(const char* fmt, ImPlotYAxis y_axis=ImPlotYAxis_1);
```

Adds SetNextPlotFormatX/Y for custom tick label formatting

---

implot.cpp
implot.h
implot_demo.cpp
implot_internal.h
implot_items.cpp

This PR addresses the needs of #192, #199, and https://github.com/epezent/implot/issues/165#issuecomment-797124733. It adds a new flag `ImPlotAxisFlags_RangeFit` that when enabled will force the axis to only fit data that is within the range of the *orthogonal* axis. When used in conjunction with `ImPlotAxisFlags_AutoFit`, the following behavior can be achieved:
@yamen, @peterwilson136, @G-Alevizos
Additionally, this PR adds `ImPlotAxisFlags_Foreground` which allows grid lines to be rendered on top of data:

Adds ImPlotAxisFlags_RangeFit and ImPlotAxisFlags_Foreground

---

implot.cpp

When painting a graph with densely labeled ticks on the X axis, it may be
necessary to add newlines in the labels to avoid label text overlap.
Reserve appropriate padding space for that.
Before this change:
After this change:

add appropriate space for X tick labels with newlines

---

implot.cpp
implot_items.cpp

Fix for 
https://github.com/ocornut/imgui/commit/c6c82b9f1de6ef3e298050656a1cf0a499d4e808
As previously, because we don't want users to have to perfectly sync ImPlot and ImGui, I did two things:
- Code in ImPlot can support older versions.
- Dear ImGui itself has a graceful redirection functions
```
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
int   GetSize()  { return GetBufSize(); } // For ImPlot: should use GetBufSize() from (IMGUI_VERSION_NUM >= 18303)
#endif
```
I expect to remove this in a few versions
- FYI: that iterating ImPool with GetSize() + GetByIndex() would be incorrect if you ever used ImPool::Remove() (which you aren't). Commit above aims to clarify that.

Fix for ImPool change in Dear ImGui version 18303+

---

README.md

Hello! I recently finished with Java bindings for ImPlot as an extension in [imgui-java](https://github.com/SpaiR/imgui-java), and I noticed the FAQ here had links to some available bindings. I thought it might be useful to provide a link for the Java bindings as well.

Add Java bindings to ReadMe

---

implot_items.cpp

Triangle winding in this line creates one triangle clockwise and another counter-clockwise. This leads to one of the triangles being culled when culling is enabled.
Clockwise
https://github.com/epezent/implot/blob/507459fd5f7d6b210ad2a8663d0ae765251fcedf/implot_items.cpp#L672-L674
Counter-clockwise
https://github.com/epezent/implot/blob/507459fd5f7d6b210ad2a8663d0ae765251fcedf/implot_items.cpp#L675-L677

PlotShaded creates Opposite triangle winding

---

TODO.md
implot.cpp
implot.h
implot_demo.cpp
implot_internal.h
implot_items.cpp

Improves performance of line rendering by ~45% by:
1) using better data indexing schemes (see issues raise in #122)
2) using SSE intrinsics for inverse sqrt (taken from https://github.com/ocornut/imgui/pull/4091)
3) forcing inlining of code in `implot_items.cpp` (consequentially also results in smaller binary sizes)
Confirmed to produce similar results for multiple compilers:

improve indexing, line rendering performance by 45%

---

implot_internal.h
implot_items.cpp

This PR Fixes warnings when built under intel compiler:
1>In file included from implot\implot.cpp:112:
1>implot/implot_internal.h(124,56): : warning : comparison with infinity always evaluates to false in fast floating point modes [-Wtautological-constant-compare]
1>static inline bool ImNanOrInf(double val) { return val == HUGE_VAL || val == -HUGE_VAL || isnan(val); }
And in general, it's not valid to compare with inf/nans when -ffastmath is used, since it is assumed to be a false comparison always.

intel compiler warning fixes (and fastmath in general)

---

implot_internal.h

This saves a few CPU cycles in SetupFinish(), which otherwise formats tick labels & spacing for disabled axes.

ImPlotAxis::WillRender(): return false if axis is disabled

---

implot.cpp
implot_internal.h

Fix freed memory read error in AddTicksTime(). Invalid read occurred when LabelTickTime() resizes ticks.TextBuffer while last_major held pointer pointing into old now freed buffer.
Fixed a warning about condition depending on uninitialized ImPlotLegend::PreviousLocation.

Fixed couple invalid memory access errors

---

.github/CMakeLists.txt
README.md
implot_internal.h
implot_items.cpp

This fixes the issue [#319](https://github.com/epezent/implot/issues/379) which stated that long double are not supported. 
As a matter of fact, `long double` as well as `unsigned long` and `signed long` are not supported when using dynamic linking: see demo repository for a minimal reproduction here : https://github.com/pthom/tmp_implot_dyn
There are two commits: 
- [the first commit](https://github.com/pthom/implot/commit/df1a5a2f7664226e32a53c4f0da8cbcf7a0d96ca) introduces a macro `INSTANTIATE_FOR_NUMERIC_TYPES` that reduces some boilerplate code around template instantiations. It provides a "setting" (`IMPLOT_INSTANTIATE_ALL_NUMERIC_TYPES`) in order to enable / disable the addition of "long double" & "signed/unsigned long". 
[All the CI …

Support long & long double, add macro INSTANTIATE_FOR_NUMERIC_TYPES (Fix #319)

---

.github/CMakeLists.txt
.github/example_implot.cpp
.github/workflows/build.yml
README.md
implot_items.cpp

This PR adds support for a custom list of supported types.
There are actually two commits. If required, the second could become a second PR. 
* 47909c04: implot_items.cpp: support types customization
adds full types customization via `-DIMPLOT_CUSTOM_NUMERIC_TYPES="(float)(double)"` for example
* 874437f9: CI: link example app, with null backend
Github's CI will now compile ImGui, compile ImPlot, link and run an example application (with no backend). This serves as a proof that specific templates instantiations are actually compiled, and that link succeeds.

Support custom numeric types

---

.github/CMakeLists.txt
README.md
implot_items.cpp

> My two cents: given full configurability (looks great!) i would suggest not adding “ IMPLOT_INSTANTIATE_ALL_NUMERIC_TYPES. For those rare types it seems reasonable to simply let the user express their needs explicitly.”
I do agree, and this PR removes them. 
--- 
> especially as it may be tempting for users and we don’t know what long double would carry in term of math runtimes. 
That is an interesting question! I made a quick study, and my findings are:
- the difference of speed between `float` and `double` can be as high as 20% (and the result do depend on the arch and compiler)
- when `double` and `long double` have the same size (8 bytes), `long double` is 20% to 30% slower (except on apple M1 processor)
- when `sizeof(long double) = 16` vs `sizeof(double) = 8`, long double can be …

Remove support for IMPLOT_INSTANTIATE_ALL_NUMERIC_TYPES

---

TODO.md
implot.cpp
implot.h
implot_demo.cpp
implot_internal.h

Adds `ImPlotLegendFlags_Sort` which allows for sorting legend item display order alphabetically.

Add ImPlotLegendFlags_Sort

---

implot.cpp

I have been experimenting with making some (non-flags) enums use typed C++ enums.
For a few types like `ImGuiKey` it seemed quite worthwhile are they are useful to see in debugger without a extra cast.
I realized `ImGuiCol` and `ImGuiStyleVar`, although less useful, could similarly be strongly typed.
I haven't push the changes to core lib as I noticed it would break build on ImPlot.
**Enclosed a few fixes to ensure it should work before and after.**
Note the PushStyleVar() signature even used an incorrect type but it didn't matter there.

Fix for allowing core imgui to use typed ImGuiCol / ImGuiStyleVar enums.

---

implot.cpp
implot.h
implot_demo.cpp

This is a followup to #347 and an update following this change in core lib:
https://github.com/ocornut/imgui/commit/fd408c97904fbf9f3b4c786318e8389de11bc681
Like with #347 this is only required for users building with `IMGUI_DISABLE_OBSOLETE_FUNCTIONS` + aiming to support a few older versions.
----
If you don't mind raising minimum imgui version to latest, you can start taking advantage of the fact that ImGuiMod_XXX values can be safely or-ed with an ImGuiKey, so stuff like:
```
ImGuiMouseButton Pan;           // LMB    enables panning when held,
ImGuiModFlags    PanMod;        // none   optional modifier that must be held for panning/fitting
```
Could become:
```
ImGuiKeyChord Pan;    // == ImGuiKey_MouseLeft | ImGuiMod_Ctrl
```
(adding Ctrl for the example but PanMod default to None).
I …

Fixes for ImGuiModFlags_XXX -> ImGuiMod_XXX (v1.89) (#347)

---

implot_demo.cpp

sprintf is marked as deprecated and/or unsafe by some compilers. For example, clang complains:
```
implot_demo.cpp:840:17: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
```
This PR replaces all calls to `sprintf` in `implot_demo.cpp` with `snprintf` to address this concern.
Addresses #421

Use snprintf instead of sprintf in implot_demo.cpp

---

implot.cpp
implot_internal.h
implot_items.cpp

Changed by
https://github.com/ocornut/imgui/commit/a1b8457cb5c9238f47fc7616e84c0775412ce556
The implot side fix should work with older imgui version, unless someone includes implot_internal.h directly without having the math operators defined (which I presume will be rare and easy to discover and fix).

Fixes for requirement to define IMGUI_DEFINE_MATH_OPERATORS before imgui.h

---

implot.cpp
implot.h
implot_demo.cpp
implot_internal.h
implot_items.cpp

Hello.  This PR is the next step of a multi-codebase crusade against using zero as a null pointer constant.  I have made a [PR for Imgui](https://github.com/ocornut/imgui/pull/6313) with similar changes.

Embrace 'nullptr'

---

implot.cpp
implot_internal.h
implot_items.cpp

Generally speaking, most non-local variables would be fetched again as the compiler needs to be conservative with any non-inline calls. So caching is desirable.
But this is particularly designed around the case of `GImPlot` being re-defined to be a thread_local variable, in which case the fetches triggers a little more platform-dependent machinery.
(PS: Aside from this, I would like to work on a mechanism for dear imgui to allow storing per-extension context pointers inside the main dear imgui context. I'll let you know if that happens.)

Avoid fetching GImPlot multiple times when possible.

---

implot.cpp

- Removed misleading/unnecessary use of `ImGuiButtonFlags_AllowItemOverlap` in `BeginSubplots()`. (#203)
- Fixes for 1.89.7 renaming + new `ImGuiButtonFlags_AllowOverlap` behavior handled by `ButtonBehavior()` fixes other items from hovering while dragging plot.
Added a bit of ifdef machinery so changes will also work with older versions of ImGui.

Fixes for AllowOverlap and internal changes in 1.89.7

---

implot_items.cpp

When sample points are outside plot area, x values are saturated to plot at least one rectangle; the problem is that ImRect::Contains the upper-left corners are checked with >= and the lower-right are checked with <, so in order to include there must be at least 1 pixel difference https://github.com/ocornut/imgui/issues/3976

PlotDigital visualization problem when you zoom x axis or few samples

---

implot.cpp

Hi,
The custom `ImGui::DragScalar` widgets used to set the min/max axis limits from the right-click context menu use a simple `%.3f` format specifier. This works well for large scales but as soon as you're plotting data in the range below `1e-3` these widgets display `0.000` but otherwise work as expected. Another problem is that large values, e.g. `5.9e9`, overflow the bounding box when they are rendered.
I changed the format specifier to `%.3g` for a practical compromise. Would that be all right to merge?

Use `%g` for the min/max sliders in the plot axis context menu

---

implot.h

GCC and Clang `-Wdouble-promotion` generates warnings for implicit promotion of float to double. This warning can be advantageous in some cases.
This PR adds an explicit cast to suppress the warning when enabled. There is no functionality change.

Explicitly promote float to double for `ImPlotPoint`

---

implot.cpp
implot.h
implot_demo.cpp

Hello again! Following #506 PR.
To be able to query states of draggable items I've added new optional arguments:
```cpp
IMPLOT_API bool DragPoint(int id, double* x, double* y, const ImVec4& col, float size = 4, ImPlotDragToolFlags flags = 0, 
bool* clicked = nullptr, bool* hovered = nullptr, bool* held = nullptr);
```
When `clicked`, `hovered` or `held` provided it will be set to results of `ImGui::ButtonBehavior` function.
Example code:
```cpp
bool is_clicked = false;
ImPlot::DragPoint(key.id, &x, &y, ImVec4(1.0f, 0.0f, 1.0f, 1.0f), line_weight, 0, &is_clicked);
if (is_clicked)
{
//process click
}
```

Ability to query point, line and rect drags for their click, hovered and held states

---

implot_items.cpp

Change indexing mod from Cols to Rows to fix bounding point implementation error.

Fix indexing logic of GetterHeatmapColMaj::operator()

---

implot.cpp
implot_items.cpp

The commit 33c5a965f55f80057f197257d1d1cdb06523e963 removed the definition for `IMGUI_DEFINE_MATH_OPERATORS` including a header guard from `implot_internal.h` and moved it into the unit files `implot.cpp` and `implot_items.cpp` but without a corresponding check whether `IMGUI_DEFINE_MATH_OPERATORS` was already defined.
When `IMGUI_DEFINE_MATH_OPERATORS` is set externally, e.g. via target compile definitions, this now leads to compiler warnings. The PR fixes these compiler warnings by reintroducing header guards for `IMGUI_DEFINE_MATH_OPERATORS`.

Reintroduce header guards for `IMGUI_DEFINE_MATH_OPERATORS` to fix compiler warnings
